[project]
name = "python-exercises-generator"
version = "0.1.0"
description = "Explore ways to automatically generate programming exercises using AI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
